language: cpp

compiler:
  - clang

before_script:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
  - sudo apt-get update -qq
  - sudo apt-get install -y libgflags-dev libgoogle-glog-dev
  - sudo apt-get install -y libstdc++-4.8-dev
  - mkdir -p out/Debug
  - cd out/Debug
  - cmake -DCMAKE_BUILD_TYPE=DEBUG ../../src

script:
  - make && make test
